name: nerf-experiments-env
channels:
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.8
  - pip
  - gxx
  - gcc=12.3.0
  - ninja
  - cuda-toolkit
  - cuda-nvcc
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - ipython
    - ipykernel
    - ipympl
    - tqdm
    - numpy
    - matplotlib
    - torch==2.0.0
    - torchvision
    - torchaudio
    - pytorch-lightning
    - nerfacc -f https://nerfacc-bucket.s3.us-west-2.amazonaws.com/whl/torch-2.0.0_cu118.html
    - tyro
    - wandb
