name: nerf-experiments-env
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - pip
  - python=3.10.8
  - gcc=12.3.0
  - gxx
  - ninja
  - cuda-toolkit
  - cuda-nvcc
  - pip:
    - ipython
    - ipykernel
    - ipympl
    - tqdm
    - numpy
    - matplotlib
    - scikit-learn
    - scipy
    - torch
    - torchvision
    - torchaudio
    - pytorch-lightning
    - nerfacc
    - wandb
